//! Byte-level parity with the reference implementation.
//!
//! These vectors were produced by running `apw`'s own `src/srp.ts` under Node
//! with fixed inputs (identity, PIN, `a`, `B`, `s`, and a fixed AES-GCM IV), then
//! recording every intermediate value. If a hash input is padded where it should
//! be minimal, or an IV lands on the wrong end of a payload, one of these fails.
//!
//! The oracle script also asserted two things about the reference itself, which
//! is why this file encodes an asymmetric framing:
//!
//! * `apw`'s `decrypt()` reads `iv || ciphertext || tag`.
//! * `apw`'s `encrypt()` emits `ciphertext || tag || iv`.

use apwh::crypto::{self, SecretBytes};
use apwh::srp::{Encoding, SrpSession};

const USERNAME: &str = "AAECAwQFBgcICQoLDA0ODw==";
const PIN: &str = "482915";
const CLIENT_PRIVATE_HEX: &str = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20";
const SALT_HEX: &str = "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf";
const SHARED_KEY_HEX: &str = "065173b9f78be309969a83095cd5911fb2d0fb9f548d36141fe182a9ff7610ca";
const M_HEX: &str = "573b79bba0030d768a592b47773a3cb6d8f0bdb9f8ea5a7566a7e7677bdfaf80";
const HAMK_HEX: &str = "4908831c6e681ebb4994606221087105574e8f9749fe524eb9668ecc0f149d17";
const AES_KEY_HEX: &str = "065173b9f78be309969a83095cd5911f";
const IV_HEX: &str = "404142434445464748494a4b4c4d4e4f";
const PLAINTEXT: &str = r#"{"ACT":5,"URL":"example.com"}"#;

/// `B`: 384 bytes of `(i % 251) + 2`, as generated by the oracle.
fn server_public_bytes() -> Vec<u8> {
    (0..384u32).map(|index| ((index % 251) + 2) as u8).collect()
}

const CLIENT_PUBLIC_HEX: &str = concat!(
    "bc0e7cf5dc3babf67dcedbb3b140aacc6cac43f4336b43bbd5de48d6ea7c8eda",
    "66924e354255225bccad9debe21182e6bb050f3ff3e6cfbb62c229379968c70c",
    "a436ad649a0b051373184215eef046f6f1f2256838f958581f6c7b2b85fa4afe",
    "326a0e8a951d4489305331aff88a136fd8d108bcc95fceb7e557c889c828bd23",
    "fb0702f053e1ca6470fb3c76bce4843fc005c7ea675740f8550212656cfc8919",
    "d9db805a434a68229e0d9dfe43fc16dc680a5ce74b77cf374353b05759bc1da3",
    "a9dabde30a4209381c87ca83d9483abdf66b86f9b1cbda9ad82c62712b87ce6f",
    "b7069b8fc8df344261821a06d0dc5106af76d4245f3f7737a94dbc484b415555",
    "dc401842d3011204553ba9f611b02bc38de26eba1a76bf8350205a62c436ba1c",
    "3c7c69d59318bd107fd1c1f5d846b3142e85a5d49e522655e020ed1bfe1e186c",
    "f923bf328f0b9b4c6a8aa3266ed9125bb98d63827110713be7803122ee4603c5",
    "4ea31863ce4b10aff31f9073cf63b94733b4f066e72d4ec35687047d5d0db160",
);

/// `iv || ciphertext || tag`: the shape the helper sends and `decrypt()` reads.
const RESPONSE_SHAPED_HEX: &str = concat!(
    "404142434445464748494a4b4c4d4e4f",
    "9c6b6679f3994c95539eca9b132a02a6b5a48e051db49852ca955624059c4c37",
    "f4a8afb15c445026d37b14a1de",
);

/// `ciphertext || tag || iv`: the shape `encrypt()` produces for requests.
const REQUEST_SHAPED_HEX: &str = concat!(
    "9c6b6679f3994c95539eca9b132a02a6b5a48e051db49852ca955624059c4c37",
    "f4a8afb15c445026d37b14a1de",
    "404142434445464748494a4b4c4d4e4f",
);

fn fixed_session() -> SrpSession {
    SrpSession::resume_handshake(
        Encoding::Base64,
        USERNAME.to_string(),
        crypto::from_bytes_be(&hex::decode(CLIENT_PRIVATE_HEX).unwrap()),
        crypto::from_bytes_be(&server_public_bytes()),
        crypto::from_bytes_be(&hex::decode(SALT_HEX).unwrap()),
    )
}

#[test]
fn client_public_key_matches_the_reference() {
    let session = fixed_session();
    assert_eq!(
        hex::encode(crypto::to_bytes_be(&session.client_public())),
        CLIENT_PUBLIC_HEX
    );
}

#[test]
fn shared_key_matches_the_reference() {
    let mut session = fixed_session();
    let shared_key = session.derive_shared_key(PIN).unwrap();
    assert_eq!(
        hex::encode(crypto::to_bytes_be(&shared_key)),
        SHARED_KEY_HEX
    );
}

#[test]
fn client_proof_and_server_proof_match_the_reference() {
    let mut session = fixed_session();
    session.derive_shared_key(PIN).unwrap();

    let m = session.compute_m().unwrap();
    assert_eq!(hex::encode(m), M_HEX);
    assert_eq!(hex::encode(session.compute_hamk(&m).unwrap()), HAMK_HEX);
}

#[test]
fn aes_key_matches_the_reference() {
    let mut session = fixed_session();
    let shared_key = session.derive_shared_key(PIN).unwrap();
    assert_eq!(
        hex::encode(crypto::aes_key(&shared_key).unwrap().as_slice()),
        AES_KEY_HEX
    );
}

#[test]
fn sealing_reproduces_the_reference_ciphertext_with_the_iv_appended() {
    let key = SecretBytes::new(hex::decode(AES_KEY_HEX).unwrap());
    let iv = hex::decode(IV_HEX).unwrap();
    let sealed = crypto::seal_with_iv(&key, PLAINTEXT.as_bytes(), &iv).unwrap();
    assert_eq!(hex::encode(sealed), REQUEST_SHAPED_HEX);
}

#[test]
fn opening_reads_the_reference_payload_with_the_iv_prefixed() {
    let key = SecretBytes::new(hex::decode(AES_KEY_HEX).unwrap());
    let opened = crypto::open(&key, &hex::decode(RESPONSE_SHAPED_HEX).unwrap()).unwrap();
    assert_eq!(String::from_utf8(opened).unwrap(), PLAINTEXT);
}

#[test]
fn a_session_seals_what_the_reference_key_can_open() {
    let mut session = fixed_session();
    session.derive_shared_key(PIN).unwrap();

    // Sealed through the session, opened with the reference AES key, after
    // moving the IV from tail to head the way the helper does.
    let sealed = session.seal(&serde_json::json!({ "ACT": 5 })).unwrap();
    let (body, iv) = sealed.split_at(sealed.len() - 16);
    let mut response = iv.to_vec();
    response.extend_from_slice(body);

    let key = SecretBytes::new(hex::decode(AES_KEY_HEX).unwrap());
    assert_eq!(crypto::open(&key, &response).unwrap(), br#"{"ACT":5}"#);
}

#[test]
fn a_wrong_pin_produces_a_different_key() {
    let mut session = fixed_session();
    let shared_key = session.derive_shared_key("482916").unwrap();
    assert_ne!(
        hex::encode(crypto::to_bytes_be(&shared_key)),
        SHARED_KEY_HEX
    );
}

#[test]
fn seal_rejects_a_wrong_length_iv() {
    let key = SecretBytes::new(hex::decode(AES_KEY_HEX).unwrap());
    assert!(crypto::seal_with_iv(&key, b"x", &[0u8; 12]).is_err());
}
